"""Geometry module: Camera models, relative poses, contracts, pointmap representations, and two-view geometry."""

from src.geometry.contracts import (
    EvaluationLevel,
    PipelineStageStatus,
    MeasurementType,
    CompletenessMetricType,
    DistortionModel,
    DistortionStatus,
    GaugeFixingPolicy,
    GeometryFailureReason,
    GeometryThresholdConfig,
    TrajectoryEvaluationProvenance,
    CameraIntrinsics,
    ExtrinsicPose,
    PointmapData,
    FeatureKeypoint,
    FeatureCorrespondences,
    TwoViewGeometryResult,
    TriangulatedTrack,
    SparseReconstructionResult,
    DenseMVSInput,
    DenseMVSOutput,
    GeometryMathContracts,
)

from src.geometry.features import (
    FeatureDetectorType,
    DescriptorMatcherType,
    MatchingStrategy,
    FeatureFailureReason,
    FeatureConfig,
    SpatialMatchDiagnostics,
    FeatureExtractionResult,
    FeatureMatchResult,
    SpatialDistributionCalculator,
    ClassicalFeatureExtractor,
    ClassicalDescriptorMatcher,
)

from src.geometry.two_view import (
    TwoViewConfig,
    TwoViewGeometryEstimator,
)

from src.geometry.sfm import (
    SfMConfig,
    CandidateEvaluation,
    SfMCamera,
    SfMTrack,
    MatchGraph,
    IncrementalSfMEngine,
)

from src.geometry.bundle_adjustment import (
    BAFailureReason,
    BundleAdjustmentConfig,
    BAReprojectionMetrics,
    BundleAdjustmentResult,
    BARotationMath,
    BATranslationDirectionMath,
    BAParameterManager,
    BAResidualCalculator,
    BASparsityStructure,
    BAPostOptimizationValidator,
    IBundleAdjustmentOptimizer,
    BAParameterLayout,
    BAResidualEvaluator,
    BundleAdjustmentEngine,
)

__all__ = [
    "EvaluationLevel",
    "PipelineStageStatus",
    "MeasurementType",
    "CompletenessMetricType",
    "DistortionModel",
    "DistortionStatus",
    "GaugeFixingPolicy",
    "GeometryFailureReason",
    "GeometryThresholdConfig",
    "TrajectoryEvaluationProvenance",
    "CameraIntrinsics",
    "ExtrinsicPose",
    "PointmapData",
    "FeatureKeypoint",
    "FeatureCorrespondences",
    "TwoViewGeometryResult",
    "TriangulatedTrack",
    "SparseReconstructionResult",
    "DenseMVSInput",
    "DenseMVSOutput",
    "GeometryMathContracts",
    "FeatureDetectorType",
    "DescriptorMatcherType",
    "MatchingStrategy",
    "FeatureFailureReason",
    "FeatureConfig",
    "SpatialMatchDiagnostics",
    "FeatureExtractionResult",
    "FeatureMatchResult",
    "SpatialDistributionCalculator",
    "ClassicalFeatureExtractor",
    "ClassicalDescriptorMatcher",
    "TwoViewConfig",
    "TwoViewGeometryEstimator",
    "SfMConfig",
    "CandidateEvaluation",
    "SfMCamera",
    "SfMTrack",
    "MatchGraph",
    "IncrementalSfMEngine",
    "BAFailureReason",
    "BundleAdjustmentConfig",
    "BAReprojectionMetrics",
    "BundleAdjustmentResult",
    "BARotationMath",
    "BATranslationDirectionMath",
    "BAParameterManager",
    "BAResidualCalculator",
    "BASparsityStructure",
    "BAPostOptimizationValidator",
    "IBundleAdjustmentOptimizer",
    "BAParameterLayout",
    "BAResidualEvaluator",
    "BundleAdjustmentEngine",
]
